# Generated by Django 2.2.5 on 2019-11-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191110_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='psd',
            field=models.CharField(max_length=50),
        ),
    ]
