# Generated by Django 2.2.5 on 2019-11-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='uername',
            new_name='username',
        ),
    ]
