# Generated by Django 2.2.5 on 2019-11-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20191119_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharefamily', models.CharField(max_length=30)),
                ('sharetitle', models.CharField(max_length=50, unique=True)),
                ('sharecontent', models.TextField()),
                ('sharetime', models.DateTimeField()),
                ('likenum', models.IntegerField(default=0)),
                ('islock', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
