# Generated by Django 2.2.5 on 2019-11-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20191120_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharenote',
            name='sharetitle',
            field=models.CharField(max_length=50),
        ),
    ]
