# Generated by Django 2.2.5 on 2019-11-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_homemsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemsg',
            name='likenum',
            field=models.IntegerField(default=0),
        ),
    ]
