# Generated by Django 2.2.5 on 2019-11-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20191123_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemsg',
            name='islike',
        ),
    ]
