# Generated by Django 2.2.5 on 2019-11-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_homemsg_islike'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemsg',
            name='createtime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
