# Generated by Django 2.2.5 on 2019-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_homemsg_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharenote',
            name='leaveword',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
