# Generated by Django 2.2.5 on 2019-11-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20191126_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemsg',
            name='usermsg',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
