# Generated by Django 3.0.3 on 2020-07-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20191210_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharenote',
            name='looknum',
            field=models.IntegerField(default=0),
        ),
    ]
