# Generated by Django 3.0.3 on 2020-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_sharenote_looknum'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemsg',
            name='looknum',
            field=models.IntegerField(default=0),
        ),
    ]
