from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('look_homepage/', views.look_homepage, name='look_homepage'),
    path('login/', views.login, name='login'),
    path('islogin/', views.islogin, name='islogin'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('loginok/', views.loginok, name='loginok'),
    path('isregister/', views.isregister, name='isregister'),
    path('registerok/', views.registerok, name='registerok'),
    path('registerlock/', views.registerlock, name='registerlock'),
    path('mynotes/', views.mynotes, name='mynotes'),
    path('mynotes/nickname/', views.nickname, name='nickname'),
    path('mynotes/isnickname/', views.isnickname, name='isnickname'),
    path('mynotes/isnotice/', views.isnotice, name='isnotice'),
    path('mynotes/handbook/', views.handbook, name='handbook'),
    path('mynotes/record_events/', views.record_events, name='record_events'),
    path('mynotes/savenotes/', views.savenotes, name='savenotes'),
    path('mynotes/editnotes/', views.editnotes, name='editnotes'),
    path('mynotes/deletenote/', views.deletenote, name='deletenote'),
    path('mynotes/sharenote/', views.sharenote, name='sharenote'),
    path('mynotes/myfollow/', views.myfollow, name='myfollow'),
    path('mynotes/publish/', views.publish, name='publish'),
    path('share/', views.share, name='share'),
    path('share/sharelike/', views.sharelike, name='sharelike'),
    path('share/look_share/', views.look_share, name='look_share'),
    path('study/', views.study, name='study'),
    path('share/leaveword/', views.leaveword, name='leaveword'),
    path('share/showword/', views.showword, name='showword'),
    path('search/', views.search, name='search'),
    path('homemsglike/', views.homemsglike, name='homemsglike'),
    path('follow/', views.follow, name='follow'),
    path('nofollow/', views.nofollow, name='nofollow'),
]
